import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Activity,
  CheckCircle2,
  Copy,
  Cpu,
  Database,
  ExternalLink,
  Flame,
  Gauge,
  Gem,
  Pause,
  Play,
  Radar,
  ShieldCheck,
  Sparkles,
  Trash2,
  Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import {
  fetchDiscoveries,
  resetHunterMemory,
  startHunter,
  stopHunter,
  useHunterStream,
  type Discovery,
  type HunterEvent,
} from "@/hooks/use-hunter-stream";

const CATEGORY_LABEL: Record<string, string> = {
  ai: "AI",
  quantum: "Quantum",
  biotech: "Biotech",
  green_energy: "Green Energy",
  space_tech: "Space-Tech",
};

const CATEGORY_COLOR: Record<string, string> = {
  ai: "border-violet-400/40 text-violet-200 bg-violet-500/10",
  quantum: "border-cyan-400/40 text-cyan-200 bg-cyan-500/10",
  biotech: "border-emerald-400/40 text-emerald-200 bg-emerald-500/10",
  green_energy: "border-lime-400/40 text-lime-200 bg-lime-500/10",
  space_tech: "border-amber-400/40 text-amber-200 bg-amber-500/10",
};

const STRATEGY_LABEL: Record<string, string> = {
  brandable_cvcv: "Brandable CVCV",
  future_suffix: "Future Suffix",
  dictionary_hack: "Dictionary Hack",
  transliteration: "Transliteration",
  prefix_root: "Prefix-Root",
  color_tech: "Color-Tech",
  vowel_start: "Vowel-Start",
  portmanteau: "Portmanteau",
  short_suffix: "Short Suffix",
};

function fmt(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(2) + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1) + "K";
  return String(n);
}

function timeAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  if (ms < 1000) return "just now";
  if (ms < 60_000) return `${Math.floor(ms / 1000)}s ago`;
  if (ms < 3_600_000) return `${Math.floor(ms / 60_000)}m ago`;
  if (ms < 86_400_000) return `${Math.floor(ms / 3_600_000)}h ago`;
  return `${Math.floor(ms / 86_400_000)}d ago`;
}

function scoreColor(score: number): string {
  if (score >= 90) return "text-emerald-300";
  if (score >= 80) return "text-cyan-300";
  if (score >= 70) return "text-amber-300";
  return "text-foreground/80";
}

function scoreBg(score: number): string {
  if (score >= 90) return "from-emerald-500/20 to-emerald-500/5 border-emerald-400/40";
  if (score >= 80) return "from-cyan-500/15 to-cyan-500/5 border-cyan-400/40";
  if (score >= 70) return "from-amber-500/15 to-amber-500/5 border-amber-400/40";
  return "from-card/40 to-card/10 border-border";
}

function tierLabel(score: number): string {
  if (score >= 90) return "S-tier diamond";
  if (score >= 80) return "A-tier brand";
  if (score >= 70) return "B-tier candidate";
  return "Watch";
}

function whyBest(d: Discovery): string[] {
  const pts: string[] = [];
  pts.push(
    `Only ${d.length} letters — short names like this regularly trade for ${d.length === 5 ? "₹50L–5Cr" : d.length === 6 ? "₹10L–1Cr" : "₹3L–30L"} on Sedo / Afternic.`,
  );
  pts.push(
    `Pattern ${d.pattern} → easy to pronounce, type, and remember (radio-test ${d.radioTest ? "passed" : "borderline"}).`,
  );
  pts.push(
    `Memorability score ${d.memorability}/100 — built from vowel rhythm, syllable count, and absence of awkward consonant clusters.`,
  );
  pts.push(
    `${CATEGORY_LABEL[d.category] ?? d.category} fits a high-velocity sector (AI, quantum, biotech, climate, space) where founders pay premium for premium .com.`,
  );
  pts.push(
    `Generated by "${STRATEGY_LABEL[d.strategy] ?? d.strategy}" — a strategy that has historically yielded the cleanest brandables in this hunter.`,
  );
  return pts;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={(e) => {
        e.stopPropagation();
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 1200);
      }}
      className="inline-flex items-center gap-1 rounded border border-border/60 px-2 py-1 text-[11px] text-muted-foreground hover:border-primary/40 hover:text-primary"
      data-testid={`copy-${text}`}
    >
      {copied ? (
        <>
          <CheckCircle2 className="h-3 w-3 text-emerald-400" /> copied
        </>
      ) : (
        <>
          <Copy className="h-3 w-3" /> copy
        </>
      )}
    </button>
  );
}

function DiamondCard({ d }: { d: Discovery }) {
  const godaddyUrl = `https://www.godaddy.com/domainsearch/find?domainToCheck=${encodeURIComponent(d.fqdn)}`;
  const afternicUrl = `https://www.afternic.com/domain/${encodeURIComponent(d.fqdn)}`;
  const points = whyBest(d);
  return (
    <article
      className={cn(
        "rounded-xl border bg-gradient-to-br p-5 transition-all hover:shadow-[0_0_0_1px_rgba(56,189,248,0.25)]",
        scoreBg(d.valueScore),
      )}
      data-testid={`diamond-${d.fqdn}`}
    >
      <header className="flex items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <div className="flex items-baseline gap-2">
            <h3
              className="font-mono text-2xl font-bold tracking-tight truncate"
              data-testid={`diamond-name-${d.fqdn}`}
            >
              {d.name}
            </h3>
            <span className="text-xl font-mono text-muted-foreground/70">.{d.tld}</span>
          </div>
          <div className="mt-2 flex flex-wrap items-center gap-2">
            <Badge
              variant="outline"
              className={cn("text-[10px] uppercase tracking-wider", CATEGORY_COLOR[d.category])}
            >
              {CATEGORY_LABEL[d.category] ?? d.category}
            </Badge>
            <Badge variant="outline" className="text-[10px] border-border/60 text-muted-foreground">
              {d.length} letters
            </Badge>
            <Badge variant="outline" className="text-[10px] border-border/60 text-muted-foreground font-mono">
              {d.pattern}
            </Badge>
            {d.radioTest && (
              <Badge
                variant="outline"
                className="text-[10px] border-emerald-400/40 text-emerald-300 bg-emerald-500/10"
              >
                Radio-test pass
              </Badge>
            )}
            <Badge
              variant="outline"
              className="text-[10px] border-cyan-400/40 text-cyan-200 bg-cyan-500/10"
              title="Verisign RDAP confirms this .com is genuinely unregistered"
            >
              <ShieldCheck className="mr-1 h-3 w-3" /> RDAP-verified free
            </Badge>
          </div>
        </div>
        <div
          className={cn(
            "shrink-0 rounded-lg border bg-background/40 px-3 py-2 text-right",
            scoreBg(d.valueScore),
          )}
        >
          <div className={cn("text-3xl font-bold leading-none tabular-nums", scoreColor(d.valueScore))}>
            {d.valueScore.toFixed(0)}
          </div>
          <div className="mt-1 text-[9px] uppercase tracking-wider text-muted-foreground">
            {tierLabel(d.valueScore)}
          </div>
        </div>
      </header>

      <section className="mt-4 rounded-md border border-border/40 bg-background/30 p-3">
        <div className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1.5 flex items-center gap-1">
          <Sparkles className="h-3 w-3 text-amber-300" /> Why this is a diamond
        </div>
        <ul className="space-y-1.5 text-[12px] leading-relaxed text-foreground/85">
          {points.map((p, i) => (
            <li key={i} className="flex gap-2">
              <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-emerald-400" />
              <span>{p}</span>
            </li>
          ))}
        </ul>
      </section>

      <section className="mt-3 rounded-md border border-border/40 bg-background/20 p-3">
        <div className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1.5">
          AI rationale
        </div>
        <p className="text-[12px] leading-relaxed text-foreground/80">{d.rationale}</p>
      </section>

      <section className="mt-3 grid grid-cols-2 gap-2 text-[11px]">
        <div className="rounded border border-border/40 bg-background/20 px-2.5 py-2">
          <div className="text-[9px] uppercase tracking-wider text-muted-foreground">DNS evidence</div>
          <div className="mt-0.5 font-mono text-foreground/80 truncate" title={d.dnsEvidence}>
            {d.dnsEvidence}
          </div>
        </div>
        <div className="rounded border border-border/40 bg-background/20 px-2.5 py-2">
          <div className="text-[9px] uppercase tracking-wider text-muted-foreground">Memorability</div>
          <div className="mt-0.5 flex items-center gap-2">
            <div className="h-1.5 flex-1 rounded bg-muted/40 overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-cyan-400 to-emerald-400"
                style={{ width: `${Math.min(100, d.memorability)}%` }}
              />
            </div>
            <span className="font-mono tabular-nums">{d.memorability}</span>
          </div>
        </div>
      </section>

      <footer className="mt-4 flex flex-wrap items-center justify-between gap-2">
        <div className="text-[10px] text-muted-foreground">
          Found {timeAgo(d.discoveredAt)} · {STRATEGY_LABEL[d.strategy] ?? d.strategy}
        </div>
        <div className="flex items-center gap-2">
          <CopyButton text={d.fqdn} />
          <a
            href={afternicUrl}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1 rounded border border-border/60 px-2 py-1 text-[11px] text-muted-foreground hover:border-primary/40 hover:text-primary"
          >
            Afternic <ExternalLink className="h-3 w-3" />
          </a>
          <a
            href={godaddyUrl}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1 rounded bg-primary/90 px-3 py-1.5 text-[11px] font-medium text-primary-foreground hover:bg-primary"
            data-testid={`register-${d.fqdn}`}
          >
            Register on GoDaddy <ExternalLink className="h-3 w-3" />
          </a>
        </div>
      </footer>
    </article>
  );
}

function HeroStat({
  icon,
  label,
  value,
  sub,
  accent = "default",
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  sub?: string;
  accent?: "default" | "emerald" | "cyan" | "amber" | "violet" | "rose";
}) {
  const accentClass =
    accent === "emerald"
      ? "from-emerald-500/20 to-emerald-500/5 border-emerald-400/40 text-emerald-300"
      : accent === "cyan"
        ? "from-cyan-500/15 to-cyan-500/5 border-cyan-400/40 text-cyan-300"
        : accent === "amber"
          ? "from-amber-500/15 to-amber-500/5 border-amber-400/40 text-amber-300"
          : accent === "violet"
            ? "from-violet-500/15 to-violet-500/5 border-violet-400/40 text-violet-300"
            : accent === "rose"
              ? "from-rose-500/15 to-rose-500/5 border-rose-400/40 text-rose-300"
              : "from-card/60 to-card/10 border-border text-foreground";
  return (
    <div className={cn("rounded-xl border bg-gradient-to-br p-4", accentClass)}>
      <div className="flex items-center justify-between">
        <span className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</span>
        <span className="opacity-70">{icon}</span>
      </div>
      <div className="mt-2 text-2xl font-bold tabular-nums leading-none">{value}</div>
      {sub && <div className="mt-1.5 text-[10px] text-muted-foreground">{sub}</div>}
    </div>
  );
}

function eventDot(kind: HunterEvent["kind"]): string {
  switch (kind) {
    case "discovery":
      return "bg-emerald-400";
    case "phase":
      return "bg-violet-400";
    case "generated":
      return "bg-cyan-400";
    case "error":
      return "bg-rose-400";
    case "info":
      return "bg-amber-400";
    default:
      return "bg-muted-foreground";
  }
}

export function Live() {
  const { events, state, connected } = useHunterStream();
  const [minScore, setMinScore] = useState(70);
  const queryClient = useQueryClient();

  const discoveriesQuery = useQuery({
    queryKey: ["discoveries", minScore],
    queryFn: () => fetchDiscoveries({ limit: 60, minScore }),
    refetchInterval: 4000,
  });

  useEffect(() => {
    if (events[0]?.kind === "discovery") {
      queryClient.invalidateQueries({ queryKey: ["discoveries"] });
    }
  }, [events, queryClient]);

  const running = state?.running ?? false;
  const totalEvaluated = state?.totalEvaluated ?? 0;
  const totalChecked = state?.totalChecked ?? 0;
  const totalDiscoveries = state?.totalDiscoveries ?? 0;
  const evaluatedPerSecond = state?.evaluatedPerSecond ?? 0;
  const checksPerSecond = state?.checksPerSecond ?? 0;
  const everSearched = state?.everSearchedSize ?? state?.recentNamesSize ?? 0;
  const rdapVerified = state?.totalRdapVerified ?? 0;
  const rdapRejected = state?.totalRdapFalsePositives ?? 0;
  const cleanupRunning = state?.cleanupRunning ?? false;
  const cleanupChecked = state?.cleanupChecked ?? 0;
  const cleanupRemoved = state?.cleanupRemoved ?? 0;
  const totalDuplicateSkips = state?.totalDuplicateSkips ?? 0;
  const effectiveMinScore = state?.effectiveMinScore ?? 70;

  const yieldPct = useMemo(() => {
    if (totalChecked === 0) return 0;
    return Math.round((totalDiscoveries / totalChecked) * 1000) / 10;
  }, [totalChecked, totalDiscoveries]);

  async function handleToggle() {
    if (running) {
      await stopHunter();
    } else {
      await startHunter(70);
    }
  }

  async function handleResetMemory() {
    await resetHunterMemory();
  }

  return (
    <div className="px-6 py-6 max-w-[1500px] mx-auto">
      {/* Header / status / controls */}
      <header className="mb-6 flex flex-wrap items-end justify-between gap-4">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold tracking-tight">Diamond Hunting Cockpit</h1>
            <span
              className={cn(
                "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider",
                connected
                  ? "border-emerald-400/40 text-emerald-300 bg-emerald-500/10"
                  : "border-rose-400/40 text-rose-300 bg-rose-500/10",
              )}
            >
              <span
                className={cn(
                  "h-1.5 w-1.5 rounded-full",
                  connected ? "bg-emerald-400 animate-pulse" : "bg-rose-400",
                )}
              />
              {connected ? "Live stream" : "Reconnecting"}
            </span>
            <span
              className={cn(
                "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider",
                running
                  ? "border-primary/50 text-primary bg-primary/10"
                  : "border-border text-muted-foreground",
              )}
            >
              {running ? "Hunter ARMED" : "Hunter idle"}
            </span>
          </div>
          <p className="mt-1.5 text-sm text-muted-foreground max-w-2xl">
            Pro-grade .com diamond finder — only 5–7 letter brandable names in deep-tech (AI, Quantum, Biotech, Green Energy, Space-Tech). Every candidate is{" "}
            <span className="text-cyan-300">DNS-checked</span> then{" "}
            <span className="text-emerald-300">Verisign RDAP confirmed</span> truly unregistered. Names already searched are remembered forever.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            onClick={handleResetMemory}
            size="sm"
            variant="outline"
            className="border-amber-400/40 text-amber-300 hover:bg-amber-500/10"
            data-testid="button-reset"
            title="Reset session counters (history is permanent and never cleared)"
          >
            <Trash2 className="mr-1 h-3.5 w-3.5" /> Reset counters
          </Button>
          <Button
            onClick={handleToggle}
            size="sm"
            variant={running ? "outline" : "default"}
            className={cn(
              running
                ? "border-rose-400/50 text-rose-300 hover:bg-rose-500/10"
                : "bg-primary text-primary-foreground hover:bg-primary/90",
            )}
            data-testid="button-toggle-hunter"
          >
            {running ? (
              <>
                <Pause className="mr-1 h-3.5 w-3.5" /> Pause
              </>
            ) : (
              <>
                <Play className="mr-1 h-3.5 w-3.5" /> Resume
              </>
            )}
          </Button>
        </div>
      </header>

      {/* Hero stats */}
      <section className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
        <HeroStat
          icon={<Flame className="h-4 w-4" />}
          label="Evaluated / sec"
          value={fmt(evaluatedPerSecond)}
          sub={`${fmt(totalEvaluated)} total · in-memory generation`}
          accent="amber"
        />
        <HeroStat
          icon={<Radar className="h-4 w-4" />}
          label="DNS / sec"
          value={fmt(checksPerSecond)}
          sub={`${fmt(totalChecked)} probed · top-scored only`}
          accent="cyan"
        />
        <HeroStat
          icon={<Gem className="h-4 w-4" />}
          label="Diamonds in vault"
          value={fmt(totalDiscoveries)}
          sub={`${yieldPct}% diamond yield · all 5–7 letter`}
          accent="emerald"
        />
        <HeroStat
          icon={<ShieldCheck className="h-4 w-4" />}
          label="RDAP verified"
          value={fmt(rdapVerified)}
          sub={`${fmt(rdapRejected)} parked/sale-page rejected`}
          accent="violet"
        />
        <HeroStat
          icon={<Database className="h-4 w-4" />}
          label="Lifetime memory"
          value={fmt(everSearched)}
          sub={`${fmt(totalDuplicateSkips)} duplicates blocked this session`}
        />
        <HeroStat
          icon={<Gauge className="h-4 w-4" />}
          label="Score gate"
          value={`≥ ${effectiveMinScore}`}
          sub={`auto-tuned · only premium brandables pass`}
        />
      </section>

      {/* Cleanup banner */}
      {cleanupRunning && (
        <div className="mb-4 flex items-center gap-2 rounded-md border border-amber-400/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-200">
          <Zap className="h-4 w-4" />
          <span>
            Background cleanup re-verifying old vault entries via Verisign RDAP — removing any that are now parked or for-sale.{" "}
            <span className="font-semibold">{cleanupChecked.toLocaleString()}</span> checked ·{" "}
            <span className="font-semibold">{cleanupRemoved.toLocaleString()}</span> removed
          </span>
        </div>
      )}

      {/* Filter strip */}
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-card/30 px-4 py-3">
        <div className="flex items-center gap-3">
          <Gem className="h-4 w-4 text-emerald-300" />
          <h2 className="text-sm font-semibold">Diamond vault</h2>
          <span className="text-xs text-muted-foreground">
            sorted by value · {discoveriesQuery.data?.items.length ?? 0} shown of{" "}
            {discoveriesQuery.data?.total.toLocaleString() ?? 0} verified
          </span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-[11px] text-muted-foreground">Show score ≥</span>
          <Slider
            value={[minScore]}
            min={50}
            max={95}
            step={5}
            onValueChange={(v) => setMinScore(v[0] ?? 70)}
            className="w-40"
            data-testid="slider-filter-score"
          />
          <span className="font-mono text-sm w-8 text-right tabular-nums">{minScore}</span>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        {/* Diamond cards grid */}
        <section>
          {discoveriesQuery.isLoading && (
            <div className="rounded-lg border border-dashed border-border/60 px-6 py-16 text-center text-sm text-muted-foreground">
              Loading diamonds…
            </div>
          )}
          {discoveriesQuery.data && discoveriesQuery.data.items.length === 0 && (
            <div className="rounded-lg border border-dashed border-border/60 px-6 py-16 text-center">
              <Gem className="mx-auto mb-3 h-10 w-10 text-muted-foreground/40" />
              <h3 className="text-base font-semibold">No diamonds at this gate yet</h3>
              <p className="mt-1 text-sm text-muted-foreground">
                Lower the score gate above, or wait — the hunter is generating thousands per second in the background.
              </p>
            </div>
          )}
          {discoveriesQuery.data && discoveriesQuery.data.items.length > 0 && (
            <div className="grid gap-4 grid-cols-1 xl:grid-cols-2">
              {discoveriesQuery.data.items.map((d) => (
                <DiamondCard key={d.id} d={d} />
              ))}
            </div>
          )}
        </section>

        {/* Live activity sidebar */}
        <aside className="lg:sticky lg:top-[74px] lg:self-start">
          <div className="rounded-lg border border-border bg-card/30">
            <div className="flex items-center justify-between border-b border-border/60 px-4 py-3">
              <div className="flex items-center gap-2">
                <Activity className="h-4 w-4 text-cyan-300" />
                <h3 className="text-sm font-semibold">Hunter telemetry</h3>
              </div>
              <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
                live
              </span>
            </div>
            {state?.currentCategory && state.currentStrategy && (
              <div className="border-b border-border/40 px-4 py-2.5 text-xs">
                <div className="flex items-center gap-1.5 text-violet-200">
                  <Cpu className="h-3.5 w-3.5" />
                  <span className="font-medium">
                    {CATEGORY_LABEL[state.currentCategory] ?? state.currentCategory}
                  </span>
                  <span className="text-muted-foreground">via</span>
                  <span className="font-medium">
                    {STRATEGY_LABEL[state.currentStrategy] ?? state.currentStrategy}
                  </span>
                </div>
                <div className="mt-1 text-[10px] text-muted-foreground">
                  Cycle #{state.cycle} · batch {state.batchSize} · concurrency {state.concurrency}
                </div>
              </div>
            )}
            <ScrollArea className="h-[520px]">
              <ul className="divide-y divide-border/40">
                {events.length === 0 && (
                  <li className="px-4 py-12 text-center text-xs text-muted-foreground">
                    Warming up…
                  </li>
                )}
                {events.slice(0, 80).map((ev) => (
                  <li
                    key={ev.id}
                    className="px-4 py-2 flex items-start gap-2 text-[11px]"
                    data-testid={`event-${ev.kind}`}
                  >
                    <span className={cn("mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full", eventDot(ev.kind))} />
                    <div className="min-w-0 flex-1">
                      <div className="leading-snug text-foreground/85 break-words">{ev.message}</div>
                      <div className="mt-0.5 text-[9px] text-muted-foreground/70 font-mono">
                        {new Date(ev.ts).toLocaleTimeString()}
                      </div>
                    </div>
                  </li>
                ))}
              </ul>
            </ScrollArea>
          </div>
        </aside>
      </div>
    </div>
  );
}
